---
# tasks file for setup-nginx-configuration

- name: Upload http server configuration
  copy:
    src: "{{ role_path }}/files/server.conf"
    dest: "/etc/nginx/sites-enabled/server.conf"


- name: Restart nginx service
  service:
    name: nginx
    state: restarted
