---
# tasks file for collaborators-file-system

- name: Setup worldcorp main dir accesses
  file:
    path: /opt/worldcorp
    owner: root
    group: monitor
    mode: 0775
    state: directory

- name: Setup worldcorp collaborators dir accesses
  file:
    path: /opt/worldcorp/collaborators
    owner: root
    group: monitor
    mode: 0755
    state: directory

- name: Setup new collaborator directory
  file:
    path: /opt/worldcorp/collaborators/new
    owner: root
    group: monitor
    mode: u=rw,g=rxw,o=r
    state: directory

- name: Setup collaborators xml directory
  file: 
    path: /opt/worldcorp/collaborators/xml
    owner: root
    group: monitor
    mode: u=rw,g=r,o=r
    state: directory

- name: Setup collaborators image directory
  file:
    path: /opt/worldcorp/collaborators/image
    owner: root
    group: monitor
    mode: u=rw,g=r,o=r
    state: directory

