---
# tasks file for upload-worldcorp-site

- name: Upload worldcorp tar source
  copy:
    src: "{{ playbook_dir }}/artifact/worldcorp.tar.gz"
    dest: /tmp/worldcorp.tar.gz

- name: Untar sources
  command: 
    cmd: "tar -xvf worldcorp.tar.gz"
    chdir: "/tmp"

- name: Create directory for prod and preprod site
  file:
    path: "/var/www/html/{{ item }}"
    state: directory
  with_items:
    - "prod"
    - "preprod"

- name: Move site to preprod
  command:
    cmd: "rsync -av /tmp/worldcorp_landing/ /var/www/html/preprod/"

- name: Move site to prod
  command:
    cmd: "rsync -av --exclude='.*/' --exclude='.gitignore' /tmp/worldcorp_landing/ /var/www/html/prod/"
