- hosts: worldcorp
  become: yes

  roles:
    - role: install-nginx
    - role: upload-worldcorp-site
    - role: setup-nginx-configuration
    - role: create-vm-user
    - role: collaborators-file-system
    - role: add-collaborators-runner
