---
# tasks file for add-collaborators-runner

- name: Upload worldcorp tar source
  copy:
    src: "{{ playbook_dir }}/artifact/openjdk-21.0.2.tar.gz"
    dest: /tmp/openjdk-21.0.2.tar.gz

- name: Untar openjdk
  command: 
    cmd: "tar -xvf openjdk-21.0.2.tar.gz"
    chdir: "/tmp"

- name: Move to opt directory
  command:
    cmd: "mv /tmp/jdk-21.0.2 /opt/jdk-21.0.2"

  
